<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Pragti" failures="1" tests="11" name="Default test" time="72.133" errors="0" timestamp="2024-11-25T12:30:27 IST">
  <testcase classname="pac1.New1Test" name="fTest" time="0.13"/>
  <testcase classname="pac1.New1Test" name="gllllTest" time="0.014">
    <failure type="java.lang.AssertionError" message="expected [jj8] but found [jj]">
      <![CDATA[java.lang.AssertionError: expected [jj8] but found [jj]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at pac1.New1Test.gllllTest(New1Test.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gllllTest -->
  <testcase classname="pac1.New1Test" name="gllllyTest" time="0.005">
    <skipped/>
  </testcase> <!-- gllllyTest -->
  <testcase classname="pac1.New1Test" name="gllllyyTest" time="0.007">
    <skipped/>
  </testcase> <!-- gllllyyTest -->
  <testcase classname="pac1.alllinksTest" name="flTest" time="0.041"/>
  <testcase classname="pac1.alllinksTest" name="fyyTest" time="0.104"/>
  <testcase classname="pac1.alllinksTest" name="kkkTest" time="0.041"/>
  <testcase classname="pac1.NewTest" name="fTest" time="13.867"/>
  <testcase classname="pac1.NewTest" name="fjwindowTest" time="13.575"/>
  <testcase classname="pac1.NewTest" name="gjjTest" time="15.02"/>
  <testcase classname="pac1.NewTest" name="gllllTest" time="13.669"/>
</testsuite> <!-- Default test -->
